version: '2'
services:
  ## Sensu stack

  sensu-api:
    build: 'sensu-api'
    environment:
      # Sensu API
      - SENSU_API_USER=ismar
      - SENSU_API_PASS=slomic
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=slomic
      # Rabbit MQ
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=ismar
      - RABBITMQ_PASS=slomic
    links:
      - rabbitmq
      - redis
    depends_on:
      - rabbitmq
      - redis
    ports:
      - "4567:4567"
    restart: always

  sensu-client:
    build: 'sensu-client'
    environment:
      # Sensu client
      - SENSU_CLIENT_NAME=test-client
      - SENSU_CLIENT_ADR=127.0.0.1
      - SENSU_CLIENT_SUBSCRIPTIONS="rabbitmq","redis"
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=slomic
      # Rabbit MQ
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=ismar
      - RABBITMQ_PASS=slomic
    links:
      - rabbitmq
      - redis
    depends_on:
      - rabbitmq
      - redis
    privileged: true
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  rabbitmq:
    image: rabbitmq:3-management
    #environment:
    #  - RABBITMQ_DEFAULT_USER=ismar
    #  - RABBITMQ_DEFAULT_PASS=slomic
    ports:
      - '8080:15672'
    restart: always

  redis:
    image: redis:3.2.4
    #environment:
    #  - REDIS_PASS=slomic
    ports:
      - '6379:6379'
    restart: always

  sensu-server:
    build: 'sensu-server'
    environment:
      # Sensu API
      - SENSU_API_HOST=sensu-api
      - SENSU_API_PORT=4567
      - SENSU_API_USER=ismar
      - SENSU_API_PASS=slomic
      # Rabbit MQ
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=ismar
      - RABBITMQ_PASS=slomic
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=slomic
      # Slack
      - SLACK_WEBHOOK_URL=
      - SLACK_ICON_URL=http://sensuapp.org/img/sensu_logo_large-c92d73db.png
      - 'SLACK_EMOJI=:screamcat:'
      # Mailgun
      - MAILGUN_APIKEY=
      - MAILGUN_DOMAIN=
      - MAILGUN_FROM=
      - MAILGUN_TO=
    links:
      - rabbitmq
      - redis
      - sensu-api
    restart: always

  uchiwa:
    build: 'uchiwa'
    environment:
      # Sensu API
      - SENSU_DC_NAME=test-datacenter
      - SENSU_API_HOST=sensu-api
      - SENSU_API_PORT=4567
      - SENSU_API_USER=ismar
      - SENSU_API_PASS=slomic
      # Uchiwa
      - UCHIWA_HTTP_USER=ismar
      - UCHIWA_HTTP_PASS=slomic
    links:
      - sensu-api
    ports:
      - '3000:3000'
    restart: always