version: '2'
services:
  ## Sensu stack

  sensu-api:
    build: 'sensu-api'
    environment:
      # Sensu API
      - SENSU_API_USER=ismar
      - SENSU_API_PASS=slomic
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=slomic
      # Rabbit MQ
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=ismar
      - RABBITMQ_PASS=slomic
    links:
      - rabbitmq
      - redis
    depends_on:
      - rabbitmq
      - redis
    ports:
      - "4567:4567"
    restart: always

  sensu-client:
    build: 'sensu-client'
    environment:
      # Sensu client
      - SENSU_CLIENT_NAME=test-client
      - SENSU_CLIENT_ADR=127.0.0.1
      - SENSU_CLIENT_SUBSCRIPTIONS="rabbitmq","redis"
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=slomic
      # Rabbit MQ
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=ismar
      - RABBITMQ_PASS=slomic
    links:
      - rabbitmq
      - redis
    depends_on:
      - rabbitmq
      - redis
    privileged: true
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  rabbitmq:
    image: 'rabbitmq:3-management'
    environment:
      - RABBITMQ_DEFAULT_USER=ismar
      - RABBITMQ_DEFAULT_PASS=slomic
    ports:
      - '8080:15672'
    restart: always

  redis:
    image: 'tutum/redis:latest'
    environment:
      - REDIS_PASS=slomic
    ports:
      - '6379:6379'
    restart: always

  sensu-server:
    build: 'sensu-server'
    environment:
      # Sensu API
      - SENSU_API_HOST=sensu-api
      - SENSU_API_PORT=4567
      - SENSU_API_USER=ismar
      - SENSU_API_PASS=slomic
      # Rabbit MQ
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=ismar
      - RABBITMQ_PASS=slomic
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=slomic
      # Carbon Relay
      - CARBON_RELAY_HOST=carbon-relay
      - CARBON_RELAY_PORT=2013
      # Slack
      - SLACK_WEBHOOK_URL=
      - SLACK_ICON_URL=http://sensuapp.org/img/sensu_logo_large-c92d73db.png
      - 'SLACK_EMOJI=:screamcat:'
      # Mailgun
      - MAILGUN_APIKEY=
      - MAILGUN_DOMAIN=
      - MAILGUN_FROM=
      - MAILGUN_TO=
    links:
      - rabbitmq
      - redis
      - sensu-api
      - carbon-relay
    restart: always

  uchiwa:
    build: 'uchiwa'
    environment:
      # Sensu API
      - SENSU_DC_NAME=test-datacenter
      - SENSU_API_HOST=sensu-api
      - SENSU_API_PORT=4567
      - SENSU_API_USER=ismar
      - SENSU_API_PASS=slomic
      # Uchiwa
      - UCHIWA_HTTP_USER=ismar
      - UCHIWA_HTTP_PASS=slomic
    links:
      - sensu-api
    ports:
      - '3000:3000'
    restart: always

  ## elasticsearch + logstash + logspout

  elasticsearch:
    build: 'elasticsearch'
    ports:
      - '9200:9200'
    volumes:
      - ./elasticsearch/config:/data/config
      - /data/logs
      - /data/data
      - /data/plugins

  logstash:
    image: 'logstash'
    command: 'logstash -e ''input { syslog { port => 5000 type => "docker" } } output { elasticsearch { hosts => "elasticsearch:9200" } }'''
    ports:
      - '5000:5000'
    links:
      - elasticsearch

  logspout:
    image: 'gliderlabs/logspout'
    entrypoint: '/bin/sh'
    command: '-c "/bin/logspout syslog://logstash:5000"'
    #deployment_strategy: every_node
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    links:
      - logstash

  ## carbon / graphite

  carbon-cache:
    image: 'dialonce/carbon-cache:latest'
    restart: always
    volumes:
      - sensu-carbon-cache-application-data:/opt/graphite/storage

  carbon-relay:
    image: 'dialonce/carbon-relay:latest'
    restart: always
    links:
      - carbon-cache
    ports:
      - '2013:2013'
    volumes:
      - sensu-carbon-application-data:/opt/graphite/storage

  graphite-web:
    image: 'dialonce/graphite-web:latest'
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - sensu-graphite-application-data:/opt/graphite/storage

volumes:
  sensu-graphite-application-data:
    external: true
  sensu-carbon-application-data:
    external: true
  sensu-carbon-cache-application-data:
    external: true